# Generated by Django 2.2.4 on 2019-08-21 15:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='order_contents',
            field=ckeditor.fields.RichTextField(verbose_name='工单内容'),
        ),
    ]
