# Generated by Django 2.2.4 on 2019-08-21 16:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0002_auto_20190821_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='result_desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='处理结果'),
        ),
    ]
