# Generated by Django 2.2.4 on 2019-08-22 08:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0003_auto_20190822_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='order_contents',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='工单内容'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='result_desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='处理结果'),
        ),
    ]
