# Generated by Django 2.2.4 on 2019-08-18 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-id'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
