# Generated by Django 2.2.4 on 2019-08-27 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymodel',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
            preserve_default=False,
        ),
    ]
